name: Reuse other workflow

on: [workflow_dispatch]

jobs:
  call-reusable-workflow:
    uses: ./.github/workflows/reusable.yml
    with:
      who-to-greet: '@octocat'
  use-output:
    runs-on: ubuntu-latest
    needs: call-reusable-workflow
    steps:
      - run: echo "The time is ${{ needs.call-reusable-workflow.outputs.current-time }}"
